-- TABLES CLEANUP

DROP TABLE OPINION_LIKE CASCADE;

DROP TABLE REPORT CASCADE;

DROP TABLE TAG CASCADE;

DROP TABLE TAG_CATEGORY CASCADE;

DROP TABLE REPORT_CATEGORY CASCADE;

DROP TABLE OPINION CASCADE;

DROP TABLE PLACE CASCADE;

DROP TABLE USER CASCADE;
